insert into tb_participante (nome,email) values('José Silva','jose@gmail.com');
insert into tb_participante (nome,email) values('Tiago Faria','tiago@gmail.com');
insert into tb_participante (nome,email) values('Maria do Rosário','maria@gmail.com');
insert into tb_participante (nome,email) values('Teresa Silva','teresa@gmail.com');
insert into tb_categoria (descricao) values ('Curso');
insert into tb_categoria (descricao) values ('Oficina');
insert into tb_atividade(nome,descricao,preco,categoria_id) values('Curso de HTML','Aprenda HTML de forma prática',80.00,1);
insert into tb_atividade(nome,descricao,preco,categoria_id) values('Oficina de Github','Controle versões de seus projetos',50.00,2);
INSERT INTO tb_participante_atividade (participante_id, atividades_id) VALUES (1, 1);
INSERT INTO tb_participante_atividade (participante_id, atividades_id) VALUES (1, 2);
INSERT INTO tb_participante_atividade (participante_id, atividades_id) VALUES (2, 1);
INSERT INTO tb_participante_atividade (participante_id, atividades_id) VALUES (3, 1);
INSERT INTO tb_participante_atividade (participante_id, atividades_id) VALUES (3, 2);
INSERT INTO tb_participante_atividade (participante_id, atividades_id) VALUES (4, 2);
INSERT INTO tb_atividade_participante (atividades_id,participantes_id) VALUES (1,1);
INSERT INTO tb_atividade_participante (atividades_id,participantes_id) VALUES (1,2);
INSERT INTO tb_atividade_participante (atividades_id,participantes_id) VALUES (1,3);
INSERT INTO tb_atividade_participante (atividades_id,participantes_id) VALUES (2,3);
INSERT INTO tb_atividade_participante (atividades_id,participantes_id) VALUES (2,4);
insert into tb_bloco (inicio,fim,atividade_id) values(TIMESTAMP WITHOUT TIME ZONE'2017-09-25T08:00:00', TIMESTAMP WITHOUT TIME ZONE '2017-09-25T11:00:00', 1);
insert into tb_bloco (inicio,fim,atividade_id) values(TIMESTAMP WITHOUT TIME ZONE'2017-09-25T14:00:00', TIMESTAMP WITHOUT TIME ZONE '2017-09-25T18:00:00', 2);
insert into tb_bloco (inicio,fim,atividade_id) values(TIMESTAMP WITHOUT TIME ZONE'2017-09-26T08:00:00', TIMESTAMP WITHOUT TIME ZONE '2017-09-26T11:00:00', 2);